aws_access_key_id: AKIAI3TJXHYHJVZGBSKA
aws_secret_access_key: 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
FOG_DIRECTORTY: igclonealertrails
AWS_REGION: ap-south-1
FB_APP_ID: 166711091676612
FB_APP_SECRET: bd1fc3a3ac97740764c66b78423fe5b5